import type { Movie } from '../types'

// Sample mock movies for development without Firebase
export const MOCK_MOVIES: Movie[] = [
  {
    tmdbId: '278',
    imdbId: 'tt0111161',
    title: 'The Shawshank Redemption',
    year: 1994,
    posterPath: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    overview: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    runtime: 142,
    genres: ['Drama', 'Crime'],
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler', 'Clancy Brown'],
    rating: 8.7,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '238',
    imdbId: 'tt0068646',
    title: 'The Godfather',
    year: 1972,
    posterPath: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.',
    runtime: 175,
    genres: ['Drama', 'Crime'],
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Robert Duvall', 'Diane Keaton'],
    rating: 8.7,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '240',
    imdbId: 'tt0071562',
    title: 'The Godfather Part II',
    year: 1974,
    posterPath: '/hek3koDUyRQq7ekWYeBc1Fqk5uP.jpg',
    overview: 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York.',
    runtime: 202,
    genres: ['Drama', 'Crime'],
    director: 'Francis Ford Coppola',
    cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall', 'Diane Keaton', 'John Cazale'],
    rating: 8.6,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '424',
    imdbId: 'tt0108052',
    title: "Schindler's List",
    year: 1993,
    posterPath: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    overview: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis during World War II.',
    runtime: 195,
    genres: ['Drama', 'History', 'War'],
    director: 'Steven Spielberg',
    cast: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley', 'Caroline Goodall', 'Jonathan Sagall'],
    rating: 8.6,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '389',
    imdbId: 'tt0050083',
    title: '12 Angry Men',
    year: 1957,
    posterPath: '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
    overview: 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
    runtime: 96,
    genres: ['Drama'],
    director: 'Sidney Lumet',
    cast: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam', 'John Fiedler', 'Jack Klugman'],
    rating: 8.5,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '129',
    imdbId: 'tt0120586',
    title: 'American History X',
    year: 1998,
    posterPath: '/c2gsmSQ2Cqv8zosqKOCwRS0GFBS.jpg',
    overview: 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.',
    runtime: 119,
    genres: ['Drama'],
    director: 'Tony Kaye',
    cast: ['Edward Norton', 'Edward Furlong', 'Beverly D\'Angelo', 'Jennifer Lien', 'Ethan Suplee'],
    rating: 8.4,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '155',
    imdbId: 'tt0468569',
    title: 'The Dark Knight',
    year: 2008,
    posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.',
    runtime: 152,
    genres: ['Drama', 'Action', 'Crime', 'Thriller'],
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Maggie Gyllenhaal'],
    rating: 8.5,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '680',
    imdbId: 'tt0110912',
    title: 'Pulp Fiction',
    year: 1994,
    posterPath: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    runtime: 154,
    genres: ['Thriller', 'Crime'],
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman', 'Bruce Willis', 'Ving Rhames'],
    rating: 8.5,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '13',
    imdbId: 'tt0109830',
    title: 'Forrest Gump',
    year: 1994,
    posterPath: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events.',
    runtime: 142,
    genres: ['Comedy', 'Drama', 'Romance'],
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Mykelti Williamson', 'Sally Field'],
    rating: 8.5,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '122',
    imdbId: 'tt0167260',
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    posterPath: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    overview: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam.',
    runtime: 201,
    genres: ['Adventure', 'Fantasy', 'Action'],
    director: 'Peter Jackson',
    cast: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen', 'Sean Astin', 'Orlando Bloom'],
    rating: 8.5,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '550',
    imdbId: 'tt0137523',
    title: 'Fight Club',
    year: 1999,
    posterPath: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    runtime: 139,
    genres: ['Drama'],
    director: 'David Fincher',
    cast: ['Edward Norton', 'Brad Pitt', 'Helena Bonham Carter', 'Meat Loaf', 'Jared Leto'],
    rating: 8.4,
    fetchedAt: new Date(),
  },
  {
    tmdbId: '27205',
    imdbId: 'tt1375666',
    title: 'Inception',
    year: 2010,
    posterPath: '/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
    overview: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    runtime: 148,
    genres: ['Action', 'Science Fiction', 'Adventure'],
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page', 'Tom Hardy', 'Ken Watanabe'],
    rating: 8.4,
    fetchedAt: new Date(),
  },
]

// Get TMDB poster URL
export function getPosterUrl(posterPath: string | null, size: 'w185' | 'w342' | 'w500' | 'original' = 'w342'): string {
  if (!posterPath) {
    return 'https://via.placeholder.com/342x513?text=No+Poster'
  }
  return `https://image.tmdb.org/t/p/${size}${posterPath}`
}

// Get IMDB URL
export function getImdbUrl(imdbId: string | null): string | null {
  if (!imdbId) return null
  return `https://www.imdb.com/title/${imdbId}/`
}
